create database colleges;
create database marks;
use colleges;
create table students(rollno int primary key,name varchar(20),age int);
select * from students;
insert into students values(101,"hemashree",23);
insert into students values(102,"bhumika",24);
insert into students values(103,"joel",25);
insert iFunctions fetching...nto students values(104,"srh",26);
drop table students;
create database employee;
use employee;
create table employee_details(emp_id int primary key,name varchar(20) not null,salary int default 25000,age int);
select * from employee_details;
insert into employee_details values(1234,"hema",15000,25);
insert into employee_details values(1235,"bhumi",15000,26);
insert into employee_details values(1236,"hema",15000,27);
drop table employee_details; 
create table department(dept_id int primary key,dept_name varchar(30));
insert into department values(210,"finance");
insert into department values(220,"hr");
insert into department values(230,"marketing");
select * from department;
create table employees(emp_id int primary key,name_emp varchar(25),salary int default 20000,department_id int,
foreign key(department_id)references department(dept_id));
insert into employees values(1234,"hema",20000,210);
insert into employees values(1235,"bhumi",30000,220);
insert into employees values(1236,"usha",40000,230);
insert into employees values(1237,"hema",50000,210);
select * from employees;
drop table employees;
select name_emp from employees where salary>45000;
select name_emp from employees where department_id=210;
select name_emp from employees where department_id<210;
select name_emp from employees where department_id>210;
select name_emp from employees where salary!=45000;
select emp_id from employees where salary>=45000;
select name_emp from employees where department_id=220 or department_id=210;
select name_emp from employees where department_id=210 AND salary>45000;
select name_emp from employees where department_id=220 or salary>35000;
select name_emp from employees where not salary=45000; 
select max(salary) from employees;
select min(salary) from employees;
select sum(salary) from employees;
select avg(salary) from employees;
select count(salary) from employees;
create table student(students_id int primary key,name varchar(20));
insert into student values(101,"hema");
insert into student values(102,"hema");
create table course(id int,course_name varchar(20)); 


